use std::env;
use std::fs;
use std::io;
use std::path::PathBuf;
use std::process::Command;

const EXTENSION_FILE_NAME: &str = "linkforge.py";

fn main() {
    if let Err(error) = run() {
        eprintln!("error: {error}");
        std::process::exit(1);
    }
}

fn run() -> io::Result<()> {
    let mut args = env::args().skip(1);
    let command = args.next().unwrap_or_else(|| "help".to_string());

    match command.as_str() {
        "install" => {
            let mut gui_exe = "linkforge-gui".to_string();
            while let Some(arg) = args.next() {
                if arg == "--gui-exe" {
                    gui_exe = args.next().ok_or_else(|| {
                        io::Error::new(io::ErrorKind::InvalidInput, "--gui-exe requires a value")
                    })?;
                } else {
                    return Err(io::Error::new(
                        io::ErrorKind::InvalidInput,
                        format!("unknown argument: {arg}"),
                    ));
                }
            }
            install(&gui_exe)
        }
        "uninstall" => uninstall(),
        "help" | "--help" | "-h" => {
            print_help();
            Ok(())
        }
        other => Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            format!("unknown command: {other}"),
        )),
    }
}

fn install(gui_exe: &str) -> io::Result<()> {
    ensure_nautilus_python_available()?;

    let target_dir = nautilus_python_extension_dir()?;
    fs::create_dir_all(&target_dir)?;

    let path = target_dir.join(EXTENSION_FILE_NAME);
    fs::write(&path, extension_contents(gui_exe))?;

    println!(
        "Installed LinkForge GNOME Files extension to {}",
        path.display()
    );
    println!("Restart GNOME Files with `nautilus -q` if the menu does not refresh.");
    Ok(())
}

fn uninstall() -> io::Result<()> {
    let path = nautilus_python_extension_path()?;
    if !path.exists() {
        println!("No LinkForge GNOME Files extension found.");
        return Ok(());
    }

    fs::remove_file(&path)?;

    println!(
        "Removed LinkForge GNOME Files extension from {}",
        path.display()
    );
    println!("Restart GNOME Files with `nautilus -q` if the menu does not refresh.");
    Ok(())
}

fn nautilus_python_extension_path() -> io::Result<PathBuf> {
    Ok(nautilus_python_extension_dir()?.join(EXTENSION_FILE_NAME))
}

fn nautilus_python_extension_dir() -> io::Result<PathBuf> {
    let home = home_dir()?;
    Ok(home
        .join(".local")
        .join("share")
        .join("nautilus-python")
        .join("extensions"))
}

fn home_dir() -> io::Result<PathBuf> {
    env::var_os("HOME")
        .or_else(|| env::var_os("USERPROFILE"))
        .map(PathBuf::from)
        .ok_or_else(|| io::Error::new(io::ErrorKind::NotFound, "HOME is not set"))
}

fn ensure_nautilus_python_available() -> io::Result<()> {
    let status = Command::new("python3")
        .arg("-c")
        .arg("import gi; gi.require_version('Nautilus', '4.0'); from gi.repository import Nautilus")
        .status();

    if matches!(status, Ok(status) if status.success()) {
        return Ok(());
    }

    Err(io::Error::new(
        io::ErrorKind::NotFound,
        "nautilus-python is required. Install your distribution's nautilus-python package, then rerun this command.",
    ))
}

fn extension_contents(gui_exe: &str) -> String {
    PYTHON_EXTENSION.replace("__LINKFORGE_GUI_EXE__", &python_string(gui_exe))
}

fn python_string(value: &str) -> String {
    format!("{value:?}")
}

const PYTHON_EXTENSION: &str = r#"# Generated by linkforge-context-menu-gnome.
import os
import subprocess

import gi

gi.require_version("Nautilus", "4.0")
from gi.repository import GObject, Nautilus


GUI_EXE = os.environ.get("LINKFORGE_GUI", __LINKFORGE_GUI_EXE__)


def _picked_source_state_path():
    state_home = os.environ.get("XDG_STATE_HOME")
    if not state_home:
        home = os.path.expanduser("~")
        state_home = os.path.join(home, ".local", "state")
    return os.path.join(state_home, "LinkForge", "picked-source.txt")


def _picked_source():
    try:
        with open(_picked_source_state_path(), "r", encoding="utf-8") as handle:
            path = handle.read().strip()
    except OSError:
        return None
    return path if path and os.path.exists(path) else None


def _file_path(file_info):
    location = file_info.get_location()
    return location.get_path() if location else None


def _first_name(paths):
    return os.path.basename(paths[0]) if paths else None


def _run_action(action, paths):
    command = [GUI_EXE, "--context-action", action, "--paths"]
    command.extend(paths)
    subprocess.Popen(
        command,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        start_new_session=True,
    )


class LinkForgeMenuProvider(GObject.GObject, Nautilus.MenuProvider):
    def get_file_items(self, *args):
        files = args[-1]
        paths = [_file_path(file_info) for file_info in files]
        paths = [path for path in paths if path]
        if not paths:
            return []

        first = files[0]
        first_is_dir = first.is_directory()
        picked = _picked_source()
        items = []

        if len(paths) == 1:
            name = _first_name(paths)
            label = f"Pick Link Source: {name}" if name else "Pick Link Source"
            items.append(self._action_item("pick-source", label, "pick-source", [paths[0]]))

        if len(paths) == 1 and first_is_dir and picked:
            items.append(self._action_item("drop-symlink", f"Create Symlink from {os.path.basename(picked)}", "drop-symlink", [paths[0]]))
            if os.path.isfile(picked):
                items.append(self._action_item("drop-hardlink", f"Create Hard Link from {os.path.basename(picked)}", "drop-hardlink", [paths[0]]))

        if len(paths) == 1:
            items.append(self._action_item("symlink", "Open Symlink in LinkForge...", "symlink", [paths[0]]))
            if not first_is_dir:
                items.append(self._action_item("hardlink", "Open Hard Link in LinkForge...", "hardlink", [paths[0]]))
                items.append(self._action_item("link-count", "Show Link Count", "link-count", [paths[0]]))
            items.append(self._action_item("siblings", "Find Hard Link Siblings...", "siblings", [paths[0]]))
            if first_is_dir:
                items.append(self._action_item("scan-groups", "Scan Hard Link Groups", "scan-groups", [paths[0]]))
                items.append(self._action_item("clone-tree", "Clone Tree Preserving Hard Links...", "clone-tree", [paths[0]]))

        return [self._root_item(items)] if items else []

    def get_background_items(self, *args):
        current_folder = args[-1]
        path = _file_path(current_folder)
        picked = _picked_source()
        if not path or not picked:
            return []

        items = [
            self._action_item("drop-symlink-background", f"Create Symlink from {os.path.basename(picked)}", "drop-symlink", [path])
        ]
        if os.path.isfile(picked):
            items.append(self._action_item("drop-hardlink-background", f"Create Hard Link from {os.path.basename(picked)}", "drop-hardlink", [path]))
        return [self._root_item(items)]

    def _root_item(self, items):
        root = Nautilus.MenuItem(
            name="LinkForge::Root",
            label="LinkForge",
            tip="Open LinkForge actions",
        )
        submenu = Nautilus.Menu()
        for item in items:
            submenu.append_item(item)
        root.set_submenu(submenu)
        return root

    def _action_item(self, name, label, action, paths):
        item = Nautilus.MenuItem(
            name=f"LinkForge::{name}",
            label=label,
            tip="Open LinkForge",
        )
        item.connect("activate", self._activate, action, paths)
        return item

    def _activate(self, _menu, action, paths):
        _run_action(action, paths)
"#;

fn print_help() {
    println!("Usage:");
    println!("  linkforge-context-menu-gnome install [--gui-exe <path-or-command>]");
    println!("  linkforge-context-menu-gnome uninstall");
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn extension_path_uses_nautilus_python_extensions() {
        let path = nautilus_python_extension_dir().unwrap();
        assert!(path.ends_with(".local/share/nautilus-python/extensions"));
    }

    #[test]
    fn generated_extension_uses_menu_provider_and_gui_exe() {
        let extension = extension_contents("/opt/linkforge/linkforge-gui");
        assert!(extension.contains("class LinkForgeMenuProvider"));
        assert!(extension.contains("Nautilus.MenuProvider"));
        assert!(extension.contains("/opt/linkforge/linkforge-gui"));
        assert!(extension.contains("--context-action"));
        assert!(extension.contains("drop-symlink"));
    }

    #[test]
    fn generated_extension_does_not_use_nautilus_scripts() {
        let extension = extension_contents("linkforge-gui");
        assert!(!extension.contains("NAUTILUS_SCRIPT_SELECTED_FILE_PATHS"));
        assert!(!extension.contains(".local/share/nautilus/scripts"));
    }
}
