use std::env;
use std::fs;
use std::io;
use std::path::PathBuf;
use std::process::Command;

const EXTENSION_FILE_NAME: &str = "linkforge.py";

fn main() {
    if let Err(error) = run() {
        eprintln!("error: {error}");
        std::process::exit(1);
    }
}

fn run() -> io::Result<()> {
    let mut args = env::args().skip(1);
    let command = args.next().unwrap_or_else(|| "help".to_string());

    match command.as_str() {
        "install" => {
            let mut gui_exe = "linkforge-gui".to_string();
            while let Some(arg) = args.next() {
                if arg == "--gui-exe" {
                    gui_exe = args.next().ok_or_else(|| {
                        io::Error::new(io::ErrorKind::InvalidInput, "--gui-exe requires a value")
                    })?;
                } else {
                    return Err(io::Error::new(
                        io::ErrorKind::InvalidInput,
                        format!("unknown argument: {arg}"),
                    ));
                }
            }
            install(&gui_exe)
        }
        "uninstall" => uninstall(),
        "help" | "--help" | "-h" => {
            print_help();
            Ok(())
        }
        other => Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            format!("unknown command: {other}"),
        )),
    }
}

fn install(gui_exe: &str) -> io::Result<()> {
    ensure_nautilus_python_available()?;

    let target_dir = nautilus_python_extension_dir()?;
    fs::create_dir_all(&target_dir)?;

    let path = target_dir.join(EXTENSION_FILE_NAME);
    fs::write(&path, extension_contents(gui_exe))?;

    println!(
        "Installed LinkForge GNOME Files extension to {}",
        path.display()
    );
    println!("Restart GNOME Files with `nautilus -q` if the menu does not refresh.");
    Ok(())
}

fn uninstall() -> io::Result<()> {
    let path = nautilus_python_extension_path()?;
    if !path.exists() {
        println!("No LinkForge GNOME Files extension found.");
        return Ok(());
    }

    fs::remove_file(&path)?;

    println!(
        "Removed LinkForge GNOME Files extension from {}",
        path.display()
    );
    println!("Restart GNOME Files with `nautilus -q` if the menu does not refresh.");
    Ok(())
}

fn nautilus_python_extension_path() -> io::Result<PathBuf> {
    Ok(nautilus_python_extension_dir()?.join(EXTENSION_FILE_NAME))
}

fn nautilus_python_extension_dir() -> io::Result<PathBuf> {
    let home = home_dir()?;
    Ok(home
        .join(".local")
        .join("share")
        .join("nautilus-python")
        .join("extensions"))
}

fn home_dir() -> io::Result<PathBuf> {
    env::var_os("HOME")
        .or_else(|| env::var_os("USERPROFILE"))
        .map(PathBuf::from)
        .ok_or_else(|| io::Error::new(io::ErrorKind::NotFound, "HOME is not set"))
}

fn ensure_nautilus_python_available() -> io::Result<()> {
    let status = Command::new("python3")
        .arg("-c")
        .arg("import gi; gi.require_version('Nautilus', '4.0'); from gi.repository import Nautilus")
        .status();

    if matches!(status, Ok(status) if status.success()) {
        return Ok(());
    }

    Err(io::Error::new(
        io::ErrorKind::NotFound,
        "nautilus-python is required. Install your distribution's nautilus-python package, then rerun this command.",
    ))
}

fn extension_contents(gui_exe: &str) -> String {
    PYTHON_EXTENSION.replace("__LINKFORGE_GUI_EXE__", &python_string(gui_exe))
}

fn python_string(value: &str) -> String {
    format!("{value:?}")
}

const PYTHON_EXTENSION: &str = r#"# Generated by linkforge-context-menu-gnome.
import json
import os
import subprocess

import gi

gi.require_version("Nautilus", "4.0")
from gi.repository import GObject, Nautilus


GUI_EXE = os.environ.get("LINKFORGE_GUI", __LINKFORGE_GUI_EXE__)


def _picked_source_state_path():
    return os.path.join(_picked_source_state_dir(), "picked-source.txt")


def _picked_sources_state_path():
    return os.path.join(_picked_source_state_dir(), "picked-sources.json")


def _picked_source_state_dir():
    state_home = os.environ.get("XDG_STATE_HOME")
    if not state_home:
        home = os.path.expanduser("~")
        state_home = os.path.join(home, ".local", "state")
    return os.path.join(state_home, "LinkForge")


def _existing_paths(paths):
    return [path for path in paths if path and os.path.exists(path)]


def _picked_sources():
    try:
        with open(_picked_sources_state_path(), "r", encoding="utf-8") as handle:
            paths = json.load(handle)
        if isinstance(paths, list):
            existing = _existing_paths([path for path in paths if isinstance(path, str)])
            if existing:
                return existing
    except (OSError, ValueError):
        pass

    try:
        with open(_picked_source_state_path(), "r", encoding="utf-8") as handle:
            path = handle.read().strip()
    except OSError:
        return []
    return _existing_paths([path])


def _picked_source_label(kind, picked):
    if not picked:
        return f"Create {kind} from Picked Source"
    if len(picked) > 1:
        suffix = "Symlinks" if kind == "Symlink" else "Hard Links"
        return f"Create {suffix} from {len(picked)} Sources"
    name = os.path.basename(picked[0])
    if kind == "Hard Link" and os.path.isdir(picked[0]):
        return f"Create Hard-Link Tree from {name}"
    return f"Create {kind} from {name}"


def _file_path(file_info):
    location = file_info.get_location()
    return location.get_path() if location else None


def _first_name(paths):
    return os.path.basename(paths[0]) if paths else None


def _run_action(action, paths, background=False):
    command = [GUI_EXE, "--context-action", action]
    if background:
        command.append("--context-background")
    command.append("--paths")
    command.extend(paths)
    subprocess.Popen(
        command,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        start_new_session=True,
    )


class LinkForgeMenuProvider(GObject.GObject, Nautilus.MenuProvider):
    def get_file_items(self, *args):
        files = args[-1]
        paths = [_file_path(file_info) for file_info in files]
        paths = [path for path in paths if path]
        if not paths:
            return []

        first = files[0]
        first_is_dir = first.is_directory()
        picked = _picked_sources()
        items = []

        if len(paths) >= 1:
            name = _first_name(paths)
            if len(paths) > 1:
                label = f"Pick {len(paths)} Link Sources"
            else:
                label = f"Pick Link Source: {name}" if name else "Pick Link Source"
            items.append(self._action_item("pick-source", label, "pick-source", paths))

        if len(paths) == 1 and first_is_dir and picked:
            items.append(self._action_item("drop-symlink", _picked_source_label("Symlink", picked), "drop-symlink", [paths[0]]))
            items.append(self._action_item("drop-hardlink", _picked_source_label("Hard Link", picked), "drop-hardlink", [paths[0]]))

        if len(files) == 2 and len(paths) == 2 and all(not file_info.is_directory() for file_info in files):
            items.append(self._action_item("same-file", "Compare Same File", "same-file", paths))

        if len(paths) == 1:
            items.append(self._action_item("symlink", "Open Symlink in LinkForge...", "symlink", [paths[0]]))
            if not first_is_dir:
                items.append(self._action_item("hardlink", "Open Hard Link in LinkForge...", "hardlink", [paths[0]]))
                items.append(self._action_item("link-count", "Show Link Count", "link-count", [paths[0]]))
            items.append(self._action_item("siblings", "Find Hard Link Siblings...", "siblings", [paths[0]]))
            if first_is_dir:
                items.append(self._action_item("scan-groups", "Scan Hard Link Groups", "scan-groups", [paths[0]]))
                items.append(self._action_item("clone-tree", "Clone Tree Preserving Hard Links...", "clone-tree", [paths[0]]))

        return [self._root_item(items)] if items else []

    def get_background_items(self, *args):
        current_folder = args[-1]
        path = _file_path(current_folder)
        picked = _picked_sources()
        if not path or not picked:
            return []

        items = [
            self._action_item("drop-symlink-background", _picked_source_label("Symlink", picked), "drop-symlink", [path], True)
        ]
        items.append(self._action_item("drop-hardlink-background", _picked_source_label("Hard Link", picked), "drop-hardlink", [path], True))
        return [self._root_item(items)]

    def _root_item(self, items):
        root = Nautilus.MenuItem(
            name="LinkForge::Root",
            label="LinkForge",
            tip="Open LinkForge actions",
        )
        submenu = Nautilus.Menu()
        for item in items:
            submenu.append_item(item)
        root.set_submenu(submenu)
        return root

    def _action_item(self, name, label, action, paths, background=False):
        item = Nautilus.MenuItem(
            name=f"LinkForge::{name}",
            label=label,
            tip="Open LinkForge",
        )
        item.connect("activate", self._activate, action, paths, background)
        return item

    def _activate(self, _menu, action, paths, background):
        _run_action(action, paths, background)
"#;

fn print_help() {
    println!("Usage:");
    println!("  linkforge-context-menu-gnome install [--gui-exe <path-or-command>]");
    println!("  linkforge-context-menu-gnome uninstall");
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn extension_path_uses_nautilus_python_extensions() {
        let path = nautilus_python_extension_dir().unwrap();
        assert!(path.ends_with(".local/share/nautilus-python/extensions"));
    }

    #[test]
    fn generated_extension_uses_menu_provider_and_gui_exe() {
        let extension = extension_contents("/opt/linkforge/linkforge-gui");
        assert!(extension.contains("class LinkForgeMenuProvider"));
        assert!(extension.contains("Nautilus.MenuProvider"));
        assert!(extension.contains("/opt/linkforge/linkforge-gui"));
        assert!(extension.contains("--context-action"));
        assert!(extension.contains("picked-sources.json"));
        assert!(extension.contains("Pick {len(paths)} Link Sources"));
        assert!(extension.contains("Create Hard-Link Tree"));
        assert!(extension.contains("same-file"));
        assert!(extension.contains("Compare Same File"));
        assert!(extension.contains("drop-symlink"));
        assert!(extension.contains("--context-background"));
    }

    #[test]
    fn generated_extension_does_not_use_nautilus_scripts() {
        let extension = extension_contents("linkforge-gui");
        assert!(!extension.contains("NAUTILUS_SCRIPT_SELECTED_FILE_PATHS"));
        assert!(!extension.contains(".local/share/nautilus/scripts"));
    }
}
